const { Product, Category } = require('./src/db.js')

let categories = [
  { name: "bubble gum"},
  { name: "lollipop"},
  { name: "caramel cookie"},
  { name: "candy"},
  { name: "chocolate"},
  { name: "wafers"},
  { name: "gummies"},
  { name: "bars"},
  { name: "biscuits"},
  { name: "cereal bars"},
  { name: "unknown"}
]
let products = [
  {
    name: "Oblea Rellena y Cubierta con Chocolate Milka Pause",
    description: "Oblea Rellena y Cubierta con Chocolate Milka Pause 45gr.",
    price: 290,
    availability: true,
    image: "https://i.postimg.cc/441WtMsN/998.jpg",
    stock: 30,
    brand: "milka",
    tacc: true,
    category: ["chocolate", "wafers"]
  },
  {
    name: "Chocolate Blanco Milka con Galletitas Oreo",
    description: "Chocolate Blanco Milka con Galletitas Oreo 20gr.",
    price: 100,
    availability: true,
    image: "https://i.postimg.cc/fW3b04xY/1388-1.jpg",
    stock: 30,
    brand: "milka",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Alfajor Milka mousse",
    description: "Alfajor Milka mousse 42 gr.",
    price: 137,
    availability: true,
    image: "https://i.postimg.cc/8PnZ56m1/image.jpg",
    stock: 30,
    brand: "milka",
    tacc: true,
    category: ["caramel cookie", "chocolate"]
  },
  {
    name: "Galletitas con chips de chocolate Jorgito",
    description: "Galletitas con chips de chocolate Jorgito 120 gr.",
    price: 130,
    availability: true,
    image: "https://i.postimg.cc/597YdNnd/image.jpg",
    stock: 30,
    brand: "jorgito",
    tacc: true,
    category: ["biscuits", "chocolate"]
  },
  {
    name: "Chicles Trident sin azúcar sabor a menta",
    description: "Chicles Trident sin azúcar sabor a menta x 18un.",
    price: 180,
    availability: true,
    image: "https://i.postimg.cc/nLFhCprg/00750610560605-L.jpg",
    stock: 30,
    brand: "trident",
    tacc: true,
    category: ["bubble gum"]
  },
  {
    name: "Galletitas Terrabusi Variedad Chocolate",
    description: "Galletitas Terrabusi Variedad Chocolate 310 gr",
    price: 290,
    availability: true,
    image: "https://i.postimg.cc/Njv943Cf/image.jpg",
    stock: 30,
    brand: "terrabusi",
    tacc: true,
    category: ["chocolate", "biscuits"]
  },
  {
    name: "Alfajor Jorgito relleno dulce de leche baño azucarado",
    description: "Alfajor Jorgito relleno dulce de leche baño azucarado x6 unidades.",
    price: 360,
    availability: true,
    image: "https://i.postimg.cc/x8y68NCR/image.jpg",
    stock: 30,
    brand: "jorgito",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Alfajorcito Jorgito chocolate con mousse",
    description: "Alfajorcito Jorgito chocolate con mousse x6 unidades.",
    price: 360,
    availability: true,
    image: "https://i.postimg.cc/h4ygPXks/image.jpg",
    stock: 30,
    brand: "jorgito",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Alfajor chocolate Jorgito",
    description: "Alfajor chocolate Jorgito 55 gr.",
    price: 120,
    availability: true,
    image: "https://i.postimg.cc/s2w70PL7/image.jpg",
    stock: 30,
    brand: "jorgito",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Chocolate Cofler con Rocklets",
    description: "Tableta chocolate leche con Rocklets Cofler 55 gr.",
    price: 290,
    availability: true,
    image: "https://i.postimg.cc/15sRfxXR/1010352.jpg",
    stock: 30,
    brand: "cofler",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Chocolate Cofler Leche",
    description: "Tableta chocolate leche Cofler 100 gr.",
    price: 521,
    availability: true,
    image: "https://i.postimg.cc/65J2c1QF/1010357.jpg",
    stock: 30,
    brand: "cofler",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Chocolate Cofler Block",
    description: "Tableta chocolate leche con maní Cofler Block 300 gr.",
    price: 1156,
    availability: true,
    image: "https://i.postimg.cc/fLPWVkV6/1010374.jpg",
    stock: 30,
    brand: "cofler",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Chocolate Cofler con Almendras",
    description: "Tableta chocolate leche con almendras Cofler 55 gr.",
    price: 290,
    availability: true,
    image: "https://i.postimg.cc/CM4mpDfP/1010350.jpg",
    stock: 30,
    brand: "cofler",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Chocolate con leche Milka",
    description: "Chocolate con leche Milka 20gr.",
    price: 100,
    availability: true,
    image: "https://i.postimg.cc/kMZmrBRb/1387-1.jpg",
    stock: 30,
    brand: "milka",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Bombón Milka chocolate leche con óreo",
    description: "Bombón Milka chocolate leche con óreo 19 gr.",
    price: 55,
    availability: true,
    image: "https://i.postimg.cc/rpdskvFV/image.jpg",
    stock: 30,
    brand: "milka",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Alfajor Milka triple mousse blanco",
    description: "Alfajor Milka triple mousse blanco 55 gr.",
    price: 190,
    availability: true,
    image: "https://i.postimg.cc/SssXJJrh/image.jpg",
    stock: 30,
    brand: "milka",
    tacc: true,
    category: ["caramel cookie", "chocolate"]
  },
  {
    name: "Chocolate Tofi Leche",
    description: "Chocolate leche relleno Tofi 55 gr.",
    price: 300,
    availability: true,
    image: "https://i.postimg.cc/Gm4BzwCP/1007466.jpg",
    stock: 30,
    brand: "tofi",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Chocolate Tofi Blanco",
    description: "Chocolate blanco relleno Tofi 55 gr.",
    price: 300,
    availability: true,
    image: "https://i.postimg.cc/P55JJGJs/1007467.jpg",
    stock: 30,
    brand: "tofi",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Chocolate Cofler Aireado Relleno Tofi",
    description: "Tableta chocolate aireado dulce de leche Tofi Cofler 70 gr.",
    price: 303,
    availability: true,
    image: "https://i.postimg.cc/zBVGjTWd/1011584.jpg",
    stock: 30,
    brand: "cofler",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Gomitas Eucalipto Billiken",
    description: "Gomitas Eucalipto Billiken 200gr",
    price: 200,
    availability: true,
    image: "https://i.postimg.cc/FHgxppR9/00249049.jpg",
    stock: 30,
    brand: "billiken",
    tacc: false,
    category: ["gummies"]
  },
  {
    name: "Gomitas Mentol Billiken",
    description: "Gomitas Mentol Billiken 200gr",
    price: 200,
    availability: true,
    image: "https://i.postimg.cc/CxCc2mzP/00055563.jpg",
    stock: 30,
    brand: "billiken",
    tacc: false,
    category: ["gummies"]
  },
  {
    name: "Caramelos Flyn Paff Uva",
    description: "Caramelos Flyn Paff Uva x16 unidades.",
    price: 265,
    availability: true,
    image: "https://i.postimg.cc/XYWWR17t/Caramelos-Flyn-Paff-Uva-144-Gr-1-3829.jpg",
    stock: 30,
    brand: "georgalos",
    tacc: false,
    category: ["candy"]
  },
  {
    name: "Alfajor Bon o Bon",
    description: "Alfajor Bon o Bon 40gr",
    price: 120,
    availability: true,
    image: "https://i.postimg.cc/Vv0nnLxr/1004303.jpg",
    stock: 30,
    brand: "bon o bon",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Mini Alfajor Bon o Bon",
    description: "Mini Alfajores Bon o Bon x6 unidades.",
    price: 368,
    availability: true,
    image: "https://i.postimg.cc/9ffRk2bx/20200922-12976.png",
    stock: 30,
    brand: "bon o bon",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Alfajor Bon o Bon",
    description: "Alfajor Bon o Bon 40gr pack x6 unidades.",
    price: 625,
    availability: true,
    image: "https://i.postimg.cc/tTDT5xdY/20200722-1006139.png",
    stock: 30,
    brand: "bon o bon",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Alfajor Bon o Bon blanco",
    description: "Alfajor Bon o Bon Blanco 40gr",
    price: 120,
    availability: true,
    image: "https://i.postimg.cc/g0Pf2B9P/20200722-1004305.png",
    stock: 30,
    brand: "bon o bon",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Oblea Bon o Bon Blanco",
    description: "Oblea Bon o Bon blanco 30 gr",
    price: 120,
    availability: true,
    image: "https://i.postimg.cc/BZh10drR/1003466.jpg",
    stock: 30,
    brand: "bon o bon",
    tacc: true,
    category: ["chocolate", "wafers"]
  },
  {
    name: "Oblea Bon o Bon Leche",
    description: "Oblea Bon o Bon leche 30 gr",
    price: 120,
    availability: true,
    image: "https://i.postimg.cc/jjR5pcSM/1003465.jpg",
    stock: 30,
    brand: "bon o bon",
    tacc: true,
    category: ["chocolate", "wafers"]
  },
  {
    name: "Chocolate Alfafort Felfort",
    description: "Chocolate Alfafort Felfort x 24u",
    price: 2516,
    availability: true,
    image: "https://i.postimg.cc/YSzNkGRx/415-caja.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Chocolate Cofler Block",
    description: "Chocolate con maní Cofler Block 38 gr.",
    price: 143,
    availability: true,
    image: "https://i.postimg.cc/JnhkWVLh/1005312.jpg",
    stock: 30,
    brand: "cofler",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Gomitas Frutales Billiken",
    description: "Gomitas Frutales Billiken 200gr",
    price: 200,
    availability: true,
    image: "https://i.postimg.cc/Kj12r4D2/00055565.jpg",
    stock: 30,
    brand: "billiken",
    tacc: false,
    category: ["gummies"]
  },
  {
    name: "Gomitas Tutti-frutti Billiken",
    description: "Gomitas Tutti-frutti Billiken 200gr",
    price: 200,
    availability: true,
    image: "https://i.postimg.cc/J43TYMYV/00055564.jpg",
    stock: 30,
    brand: "billiken",
    tacc: false,
    category: ["gummies"]
  },
  {
    name: "Bananina Felfort",
    description: "Bananina Felfort x 30u",
    price: 1917,
    availability: true,
    image: "https://i.postimg.cc/bwd4ZPWb/840-caja.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Bocadito Delicia Felfort",
    description: "Bocadito Delicia Felfort x 48u",
    price: 1690,
    availability: true,
    image: "https://i.postimg.cc/L6517QGv/680-caja.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Bocadito Marroc Felfort",
    description: "Bocadito Marroc Felfort x 60u",
    price: 3453,
    availability: true,
    image: "https://i.postimg.cc/j2KhP6jm/610-caja.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Bocadito Marroc Felfort",
    description: "Bocadito Marroc Felfort x 20u",
    price: 1285,
    availability: true,
    image: "https://i.postimg.cc/tJPLCNMc/612-caja-1.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Bombones Ferrero Rocher",
    description: "Bombón Ferrero Rocher x 12u",
    price: 1345,
    availability: true,
    image: "https://i.postimg.cc/vZYF1Q88/ferrero-rocher-t12-150g1-7465039ddf4c28616016129038951747-640-0.png",
    stock: 30,
    brand: "ferrero",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Bocadito Bonafide Dulce de Leche",
    description: "Bocadito Bonafide Dulce de Leche 16gr",
    price: 145,
    availability: true,
    image: "https://i.postimg.cc/rpMkXpT1/image.jpg",
    stock: 30,
    brand: "bonafide",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Chocolate Dos Corazones Felfort",
    description: "Chocolate Dos Corazones Felfort x 20u",
    price: 1861,
    availability: true,
    image: "https://i.postimg.cc/fRjBCTF1/750-caja.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Chocolate Nestlé Crunch",
    description: "Chocolate Nestlé Crunch 22gr",
    price: 131,
    availability: true,
    image: "https://i.postimg.cc/Fs504tfr/226672-chocolate-nestle-crunch-x-22-5-g-imagen-1.jpg",
    stock: 30,
    brand: "nestle",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Chocolate Nestlé con Maní",
    description: "Chocolate Nestlé con Maní 33gr",
    price: 161,
    availability: true,
    image: "https://i.postimg.cc/sDhG6TKk/221885-chocolate-nestle-con-mani-x-30-g-imagen-1.jpg",
    stock: 30,
    brand: "nestle",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Caramelos Masticables Frutales Arcor",
    description: "Caramelos Masticables Frutales Arcor Bolsa 800gr",
    price: 986,
    availability: true,
    image: "https://i.ibb.co/5Y4PsN9/20200630-1001782.jpg",
    stock: 30,
    brand: "arcor",
    tacc: false,
    category: ["candy"]
  },
  {
    name: "Caramelos Masticables Yogus",
    description: "Caramelos Masticables Yogus Bolsa 396gr",
    price: 490,
    availability: true,
    image: "https://i.ibb.co/tX3cST8/20220428-11795.jpg",
    stock: 30,
    brand: "arcor",
    tacc: false,
    category: ["candy"]
  },
  {
    name: "Caramelos Fresh Cristal Arcor",
    description: "Caramelos duros Fresh Cristal arcor Bolsa 405gr",
    price: 722,
    availability: true,
    image: "https://i.ibb.co/3SLq2Rp/20200722-1011835.png",
    stock: 30,
    brand: "arcor",
    tacc: false,
    category: ["candy"]
  },
  {
    name: "Mix surtido de Dientes, tiburones y ositos mogul",
    description: "Mix surtido de Dientes, tiburones y ositos mogul 200gr",
    price: 399,
    availability: true,
    image: "https://i.ibb.co/J5K1d9H/20210623-13288.png",
    stock: 30,
    brand: "mogul",
    tacc: false,
    category: ["candy"]
  },
  {
    name: "Alfajor Tofi Negro Triple",
    description: "Alfajor Tofi Negro Triple 73gr",
    price: 180,
    availability: true,
    image: "https://i.ibb.co/hyLmGwK/1004848.jpg",
    stock: 30,
    brand: "tofi",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Chocolate Taza Godet Semi Amargo",
    description: "Tableta de chocolate Godet Semi Amargo 100gr",
    price: 214,
    availability: true,
    image: "https://i.ibb.co/nQ2dK62/20200630-1003222.png",
    stock: 30,
    brand: "godet",
    tacc: false,
    category: ["chocolate", "bars"]
  },
  {
    name: "Chocolate Barrita Aguila 60% Cacao",
    description: "Chocolate Barra Aguila 60% Cacao 14gr",
    price: 588,
    availability: true,
    image: "https://i.ibb.co/19Tws7v/20200630-1011601.png",
    stock: 30,
    brand: "aguila",
    tacc: false,
    category: ["chocolate", "bars"]
  },
  {
    name: "Alfajor Águila Minitorta coco",
    description: "Alfajor Águila Minitorta coco 70.5gr",
    price: 180,
    availability: true,
    image: "https://i.ibb.co/xm3kScJ/20220613-13360.jpg",
    stock: 30,
    brand: "aguila",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Chicle Topline 7 Bubble Fun",
    description: "Chicles Topline Seven Bubble Fun 14g",
    price: 120,
    availability: true,
    image: "https://i.ibb.co/swvLkf5/20221027-13792.jpg",
    stock: 30,
    brand: "topline",
    tacc: true,
    category: ["bubble gum"]
  },
  {
    name: "Chicle Topline 7 Mandarina",
    description: "Chicles Seven Mandarina 14gr",
    price: 120,
    availability: true,
    image: "https://i.ibb.co/sRwmgzv/20200722-1003269.png",
    stock: 30,
    brand: "topline",
    tacc: true,
    category: ["bubble gum"]
  },
  {
    name: "Ositos frutales",
    description: "Ositos frutales 150gr",
    price: 344,
    availability: true,
    image: "https://i.ibb.co/26LM1fq/20210623-13287.png",
    stock: 30,
    brand: "mogul",
    tacc: false,
    category: ["candy"]
  },
  {
    name: "Alfajor Tofi Negro",
    description: "Alfajor tofi Chocolate 46gr",
    price: 120,
    availability: true,
    image: "https://i.ibb.co/KzRpQRc/1011661.jpg",
    stock: 32,
    brand: "tofi",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Chupelatín Felfort",
    description: "Chupelatín Felfort x 32u",
    price: 2813,
    availability: true,
    image: "https://i.postimg.cc/h49xT7Tb/970-caja.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate", "lollipop"]
  },
  {
    name: "Paragüitas Felfort",
    description: "Paragüitas Felfort x 20u",
    price: 1382,
    availability: true,
    image: "https://i.postimg.cc/CL1tzYf0/952-caja.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate", "lollipop"]
  },
  {
    name: "Mentitas Felfort",
    description: "Mentitas Felfort x 30u",
    price: 2010,
    availability: true,
    image: "https://i.postimg.cc/2SHSnC0x/830-caja.jpg",
    stock: 30,
    brand: "felfort",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Bombones Ferrero Rocher",
    description: "Bombón Ferrero Rocher x 24u",
    price: 2570,
    availability: true,
    image: "https://i.postimg.cc/rFbxspNx/ferrero-rocher-t241-1be81654fd7c8becce16129040067958-640-0.png",
    stock: 30,
    brand: "ferrero",
    tacc: true,
    category: ["chocolate"]
  },
  {
    name: "Mogul Moras Corazón",
    description: "Gomitas mogul Moras Corazón Bolsa 250gr",
    price: 724,
    availability: true,
    image: "https://i.ibb.co/c6vzTjy/1012353.jpg",
    stock: 30,
    brand: "mogul",
    tacc: false,
    category: ["gummies"]
  },
  {
    name: "Chocolate Cofler Aireado Almendras",
    description: "Tableta Chocolate Almendras cofler Air 55gr",
    price: 508,
    availability: true,
    image: "https://i.ibb.co/9gXhvD1/20220824-10343.jpg",
    stock: 30,
    brand: "cofler",
    tacc: true,
    category: ["chocolate", "bars"]
  },
  {
    name: "Alfajor Cofler Block",
    description: "Alfajor cofler Block 60gr",
    price: 180,
    availability: true,
    image: "https://i.ibb.co/cYB8M9S/1006596.jpg",
    stock: 30,
    brand: "cofler",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Mogul Extreme Tubitos Flla",
    description: "mogul Extreme Tubitos Flla 1 un x 70g",
    price: 70,
    availability: true,
    image: "https://i.ibb.co/7KrLz3p/20221027-13411.jpg",
    stock: 30,
    brand: "mogul",
    tacc: true,
    category: ["gummies"]
  },
  {
    name: "Mogul Tiburoncitos",
    description: "Gomitas mogul Tiburon 30gr",
    price: 250,
    availability: true,
    image: "https://i.ibb.co/8XBcKyw/1002001.jpg",
    stock: 30,
    brand: "mogul",
    tacc: false,
    category: ["gummies"]
  },
  {
    name: "Alfajor ByN Blanco Triple",
    description: "Alfajor BYN Blanco Triple 73,5gr",
    price: 180,
    availability: true,
    image: "https://i.ibb.co/1qSHFQh/1009919.jpg",
    stock: 30,
    brand: "bagley",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Alfajor Bon o Bon Triple",
    description: "Alfajor Bon o Bon Triple 60gr",
    price: 180,
    availability: true,
    image: "https://i.ibb.co/dcMrV34/1006140.jpg",
    stock: 30,
    brand: "bon o bon",
    tacc: true,
    category: ["chocolate", "caramel cookie"]
  },
  {
    name: "Chocolate Taza Godet Semi Amargo",
    description: "Tableta de chocolate Godet Semi Amargo 100gr",
    price: 273,
    availability: true,
    image: "https://i.ibb.co/BHhLxJ4/20220329-13437.png",
    stock: 30,
    brand: "godet",
    tacc: false,
    category: ["chocolate", "bars"]
  },
  {
    name: "Mogul Extreme Sandias",
    description: "Gomitas mogul Sandias ácidas 50gr",
    price: 130,
    availability: true,
    image: "https://i.ibb.co/WyK3NZ4/1013024.jpg",
    stock: 30,
    brand: "mogul",
    tacc: false,
    category: ["gummies"]
  },
  {
    name: "Chocolate Arcor Leche con maní",
    description: "Chocolate con leche y maní Arcor 25 gr",
    price: 120,
    availability: true,
    image: "https://i.ibb.co/VHHYC9d/1012576.jpg",
    stock: 30,
    brand: "arcor",
    tacc: false,
    category: ["chocolate", "bars"]
  },
  {
    name: "Chocolate Taza Aguila Semi Amargo",
    description: "Tableta chocolate semi amargo Aguila 150gr.",
    price: 463,
    availability: true,
    image: "https://i.ibb.co/PQhMSB6/1012901.jpg",
    stock: 30,
    brand: "aguila",
    tacc: false,
    category: ["chocolate", "bars"]
  },
  {
    name: "Chocolate Aguila 70% Cacao",
    description: "Tableta Aguila 70% Cacao 150 gr",
    price: 642,
    availability: true,
    image: "https://i.ibb.co/PWq5WSM/1012903.jpg",
    stock: 30,
    brand: "aguila",
    tacc: false,
    category: ["chocolate", "bars"]
  },
  {
    name: "Chocolate Taza Aguila Semi Amargo",
    description: "Tableta chocolate semi amargo aguila 225gr",
    price: 649,
    availability: true,
    image: "https://i.ibb.co/ZHHJmhh/1010582.jpg",
    stock: 30,
    brand: "aguila",
    tacc: false,
    category: ["chocolate", "bars"]
  },
  {
    name: "Barra Cereal Mix Yoghurt Vainilla",
    description: "Barra Cereal Mix Yoghurt Vainilla 26gr",
    price: 120,
    availability: true,
    image: "https://i.ibb.co/4JtNgTf/20220203-12628.png",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["cereal bars"]
  },
  {
    name: "Cereales Bagley Salvado",
    description: "Cereales bagley Salvado 169gr",
    price: 171,
    availability: true,
    image: "https://i.ibb.co/cC4x2YZ/20220420-13625.jpg",
    stock: 30,
    brand: "bagley",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Pepas Receta de la Abuela",
    description: "Pepas Recetas de la Abuela 183gr",
    price: 160,
    availability: true,
    image: "https://i.ibb.co/5Mh6qjW/20220204-13589.png",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Barra Cereal Mix Chocolate y Almendras",
    description: "Barra Cereal Mix Chocolate y Almendras 23gr",
    price: 120,
    availability: true,
    image: "https://i.ibb.co/sF1kFHn/20220203-3789.png",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["cereal bars"]
  },
  {
    name: "Barra Cereal Mix Relleno Frutilla",
    description: "Barra Cereal Mix Relleno Frutilla",
    price: 130,
    availability: true,
    image: "https://i.ibb.co/pf07tc0/20220203-2582.png",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["cereal bars"]
  },
  {
    name: "Galletitas Surtidas Bagley",
    description: "Surtido bagley 398gr",
    price: 373,
    availability: true,
    image: "https://i.ibb.co/rfTVWSD/20221104-13889.jpg",
    stock: 30,
    brand: "bagley",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Galletitas Surtidas Diversión",
    description: "Surtido bagley 398gr",
    price: 335,
    availability: true,
    image: "https://i.ibb.co/5xw4KR9/20221104-13890.jpg",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Galletitas Chocolinas",
    description: "Galletitas Chocolinas 262gr",
    price: 286,
    availability: true,
    image: "https://i.ibb.co/9pb5ZCL/20221101-13940.jpg",
    stock: 30,
    brand: "bagley",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Saladix Horneados Barbacoa",
    description: "Saladix Horneados Barbacoa 100gr",
    price: 178,
    availability: true,
    image: "https://i.ibb.co/3chM12x/20220923-13828.jpg",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Cereal Mix Semillas y Chips de chocolate",
    description: "Cereal Mix Semillas y Chips de chocolate 207gr",
    price: 275,
    availability: true,
    image: "https://i.ibb.co/zhgqZvW/20220420-13575.jpg",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Cereal Mix Avena y Manzana",
    description: "Cereal Mix Avena y Manzana 180gr",
    price: 227,
    availability: true,
    image: "https://i.ibb.co/zPJxTZm/20220420-13579.jpg",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["biscuits"]
  },

  {
    name: "Mini Macucas Bolsa",
    description: "Mini Macucas Bolsa 85gr",
    price: 178,
    availability: true,
    image: "https://i.ibb.co/0fRC8g6/20220222-13371.png",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Obleas Opera",
    description: "Obleas Opera Sabor Original 220gr",
    price: 340,
    availability: true,
    image: "https://i.ibb.co/qkGJ6v6/20220203-9509.png",
    stock: 30,
    brand: "bagley",
    tacc: true,
    category: ["biscuits", "wafers"]
  },
  {
    name: "Macucas chips",
    description: "Macucas Chips 118gr",
    price: 126,
    availability: true,
    image: "https://i.ibb.co/pJV5Gwx/20220204-13098.jpg",
    stock: 30,
    brand: "arcor",
    tacc: true,
    category: ["biscuits"]
  },
  {
    name: "Caramelos Mini arcor Cherry",
    description: "Caramelos duros Mini arcor Cherry Bolsa 800gr",
    price: 1300,
    availability: true,
    image: "https://i.ibb.co/zSDw03y/20200722-1012852.png",
    stock: 30,
    brand: "arcor",
    tacc: false,
    category: ["candy"]
  }
]

module.exports = async function loadProductsAndCategories() {
  let allCategories = await Category.findAll();
  !allCategories.length && await Category.bulkCreate(categories);
  for(let i=0; i<products.length; i++) {
    let product = await Product.create(products[i]);
    let categoryProduct = await Category.findAll({ where: { name: products[i].category } });
    await product.addCategories(categoryProduct);
  }
  return await Product.findAll({ include: { model: Category}})
}